// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package inject

import (
	"my-project/internal"
	"my-project/internal/app"
	"my-project/internal/config"
)

// Injectors from wire.go:

func InitApp(env string) (*internal.App, func(), error) {
	configConfig, err := config.NewConfig(env)
	if err != nil {
		return nil, nil, err
	}
	enter := app.NewEnter(configConfig)
	internalApp := internal.NewApp(enter)
	return internalApp, func() {
	}, nil
}
